Downgrade to GraalVM 20.0.0
Previously, the generated Bloop configuration file of test targets would
not include the dependency on `org.scalameta:junit-interface`, because
the resolution would fail under GraalVM 20.1.0 with the following error:

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Invoke with
MethodHandle argument could not be reduced to at most a single call or
single field access. The method handle must be a compile time constant,
e.g., be loaded from a `static final` field. Method that contains the
method handle invocation:
java.lang.invoke.LambdaForm$MH/2143945824.invoke_MT(Object, Object)
```

This error doesn't happen with previous version of GraalVM.